### ISSUE TITLE
Rebuilding from slow data sources results in client time out

### ISSUE THREAD

**Issue by atlasmapper** [atlasmapper/atlasmapper#103]
When a data source has many references to metadata records the server admin client times out on its connection resulting in a poor error message like:

> An error occurred while rebuilding the data source xxxxxxxxxxx
> You'r trying to decode an invalid JSON String: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

The server admin client should you polling to communicate with the server to get a status of the dataset regeneration status.

**Comment by gaellafond** [comment]
I could implement WebSockets, but since it's not strait forward to setup, the AtlasMapper should fallback to interval requests when WebSockets is not available.

Since this application do not need to have real-time feedback, implement WebSockets would be overkill.

The interval requests will be a fantastic improvement.

**Comment by gaellafond** [comment]
Fixed in v2.0.0
